"""Render the README dashboard block from committed repo state.

The README is the front page, so everything it shows must come from a real
artifact. There is deliberately no fallback that invents numbers: if no
forecast has been published, the block says so. A grid of placeholder scores on
the front page is worse than an empty one, because it looks authoritative.

Run after any forecast or import. `--check` fails if the README is stale.
"""
from __future__ import annotations

import datetime
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
START = "<!-- DASHBOARD:START - generated by scripts/render_dashboard.py, do not edit -->"
END = "<!-- DASHBOARD:END -->"

HORIZONS = ("day", "week", "month")
RUNS_BEFORE_AUTOMATION = 10


def latest_forecast() -> dict | None:
    d = ROOT / "data/forecasts"
    files = sorted(p for p in d.glob("*.json") if p.is_file())
    if not files:
        return None
    best = max(files, key=lambda p: (json.loads(p.read_text(encoding="utf-8"))["as_of_date"],
                                     p.name))
    doc = json.loads(best.read_text(encoding="utf-8"))
    doc["_path"] = "data/forecasts/" + best.name
    return doc


def forecast_count() -> int:
    return len(list((ROOT / "data/forecasts").glob("*.json")))


def evaluation_count() -> int:
    return len(list((ROOT / "data/evaluations").glob("*.json")))


def latest_snapshot() -> dict | None:
    root = ROOT / "data/weekly_research"
    dirs = [d for d in root.iterdir() if d.is_dir() and (d / "manifest.json").is_file()]
    if not dirs:
        return None
    best = max(dirs, key=lambda d: d.name)
    return json.loads((best / "manifest.json").read_text(encoding="utf-8"))


def render_heatmap(doc: dict) -> list[str]:
    scores = doc["scores"]
    lines = [
        "| Sector | Day | Week | Month | Confidence | Why |",
        "|---|---:|---:|---:|---|---|",
    ]
    for sector in sorted(scores):
        row = scores[sector]
        cells = ["n/a" if row[h]["score"] is None
                 else str(row[h]["score"]) + " " + row[h]["rating"]
                 for h in HORIZONS]
        why = "; ".join(row["week"]["why"][:2]) or "No rationale logged"
        lines.append(
            "| " + sector + " | " + " | ".join(cells) + " | "
            + row["week"]["confidence"] + " | " + why + " |"
        )
    return lines


def render_constraints() -> list[str]:
    overrides = yaml.safe_load(
        (ROOT / "config/watchlist_overrides.yaml").read_text(encoding="utf-8"))
    baskets = yaml.safe_load(
        (ROOT / "config/sector_baskets.yaml").read_text(encoding="utf-8"))
    sector_of = {t: s for s, ts in baskets.items()
                 if s not in ("version", "note") for t in ts}
    out: list[str] = []
    sessions = overrides["minimum_sessions"]
    for ticker, meta in sorted((overrides.get("listings") or {}).items()):
        blocked = meta.get("insufficient_history_for") or []
        if not blocked:
            continue
        first = meta["first_trade_date"]
        if isinstance(first, str):
            first = datetime.date.fromisoformat(first)
        clears = first + datetime.timedelta(days=int(sessions["month"] / 21 * 30.4))
        sector = sector_of.get(ticker, "unknown sector")
        rank = baskets.get(sector, [])
        position = (" largest constituent" if rank and rank[0] == ticker
                    else " constituent")
        out.append(
            "- **" + ticker + "** (" + sector + position + ") listed "
            + first.isoformat() + ". Month-horizon metrics "
            + ", ".join("`" + b + "`" for b in blocked)
            + " are not computable until " + clears.isoformat() + ". "
            + sector + " must exclude it at that horizon and record a denominator "
            "of 9, or set `data_quality.status` to `warn`."
        )
    return out


def build() -> str:
    lines = [START, "", "## Dashboard", ""]

    doc = latest_forecast()
    if doc is None:
        lines += [
            "**Latest forecast:** none published.",
            "",
            "No artifact exists in `data/forecasts/`. Nothing is rendered here rather",
            "than showing placeholder scores, which `examples/sectors/README.md`",
            "forbids committing as a forecast. Run `src/heatmap.py` on a dated,",
            "source-backed input and this table fills in.",
        ]
    else:
        regime = doc["regime"]
        lines += [
            "**As of " + doc["as_of_date"] + "** (" + doc["run_type"] + ")  ",
            "**Regime:** " + regime["label"] + ", confidence " + regime["confidence"] + "  ",
            "**Artifact:** `" + doc["_path"] + "`",
            "",
        ]
        lines += render_heatmap(doc)
        lines += [
            "",
            "Score is out of 100. Confidence is independent of score: a high score",
            "with thin evidence or a wide component spread reads lower. Bands are in",
            "`config/score_weights.yaml`.",
        ]

    runs = forecast_count()
    evals = evaluation_count()
    lines += [
        "",
        "### Run status",
        "",
        "| | |",
        "|---|---|",
        "| Forecast artifacts | " + str(runs) + " |",
        "| After-close evaluations | " + str(evals) + " |",
        "| Manual runs before automation | " + str(min(runs, RUNS_BEFORE_AUTOMATION))
        + " of " + str(RUNS_BEFORE_AUTOMATION) + " |",
        "| Scheduled jobs | none enabled |",
    ]

    snap = latest_snapshot()
    if snap is None:
        lines += ["| Weekly research snapshot | none imported |"]
    else:
        verified = "verified" if snap.get("provenance_verified") else "UNVERIFIED"
        lines += [
            "| Weekly research snapshot | " + snap["as_of_date"] + ", upstream `"
            + snap["source_commit_sha"][:7] + "`, " + str(len(snap["files"]))
            + " files, provenance " + verified + " |",
        ]

    constraints = render_constraints()
    if constraints:
        lines += ["", "### Standing data-quality constraints", ""] + constraints

    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("README.md has no DASHBOARD markers")
        return 1
    head = text[: text.index(START)]
    tail = text[text.index(END) + len(END):]
    updated = head + build() + tail

    if "--check" in sys.argv:
        if updated != text:
            print("README dashboard is stale. Run: python scripts/render_dashboard.py")
            return 1
        print("README dashboard is up to date.")
        return 0

    README.write_text(updated, encoding="utf-8", newline="\n")
    print("Updated the README dashboard block.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
