"""Render the README daily-tape block from committed repo state.

Same contract as scripts/render_dashboard.py: everything shown comes from a
real artifact, there is no fallback that invents numbers, and `--check` fails
if the README has drifted from what the artifacts say.

Two surfaces, two rules, inherited from the dashboard renderer:
  * the fenced chart is aligned by padding, so it uses block characters only
    -- they are single-width in a monospace font. Emoji are double-width and
    would shear the columns.
  * the markdown table is where emoji belong, because nothing lines up there.

The block is explicit that it is an observation. The dashboard block above it
renders a forecast; these two sit on the same page and must never be confusable.

The comparison rows -- gold, the US dollar, bitcoin -- render as their own
markdown table under the sector chart, headed as not sectors. They are kept
out of the chart on purpose: sharing its bar scale would let one volatile row
flatten eleven sector bars, and sharing its columns would put them where a
breadth and an up-volume figure are expected. A value the tape does not carry
renders as `missing`, including every row of a tape that predates them.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import daily_tape as dt  # noqa: E402
import macro_comparisons as mc  # noqa: E402
import regime_prior as rp  # noqa: E402

README = ROOT / "README.md"
START = "<!-- TAPE:START - generated by scripts/render_tape.py, do not edit -->"
END = "<!-- TAPE:END -->"

HALF = 7          # cells either side of the zero axis
FULL = "█"   # full block
EMPTY = "·"  # middle dot, single-width
AXIS = "│"   # box-drawing vertical
RULE = "─"   # box-drawing horizontal


def latest_tape() -> dict | None:
    d = ROOT / "data/tape"
    if not d.is_dir():
        return None
    files = sorted(p for p in d.glob("*.json") if p.is_file())
    if not files:
        return None
    doc = json.loads(files[-1].read_text(encoding="utf-8"))
    doc["_path"] = "data/tape/" + files[-1].name
    return doc


def diverging_bar(value, scale) -> str:
    """A zero-centred bar. Left of the axis is negative, right is positive."""
    if value is None or not scale:
        return EMPTY * HALF + AXIS + EMPTY * HALF
    cells = int(round(min(abs(value) / scale, 1.0) * HALF))
    if value < 0:
        return EMPTY * (HALF - cells) + FULL * cells + AXIS + EMPTY * HALF
    return EMPTY * HALF + AXIS + FULL * cells + EMPTY * (HALF - cells)


def signed(value, places=2) -> str:
    if value is None:
        return "n/a"
    return format(value, "+." + str(places) + "f")


def render_chart(tape: dict, cmp_block: dict | None) -> list[str]:
    rows = []
    for sector, horizons in tape["sectors"].items():
        block = horizons.get("week") or {}
        rows.append((block.get("sector_return_vs_spy_pct"), sector, block))
    rows.sort(key=lambda r: (r[0] is None, -(r[0] or 0)))

    scale = max((abs(r[0]) for r in rows if r[0] is not None), default=1.0)

    width = max(len(r[1]) for r in rows)
    head = ("SECTOR".ljust(width) + "  " + "5d vs SPY".center(2 * HALF + 1)
            + "   " + "EXCESS".rjust(7) + "  " + "BRDTH".rjust(6)
            + "  " + "UPVOL".rjust(6))
    if cmp_block:
        head += "  " + "PRIOR".rjust(6) + "  " + "RANK".rjust(11)
    lines = [head, RULE * len(head)]

    for excess, sector, block in rows:
        line = (sector.ljust(width) + "  " + diverging_bar(excess, scale)
                + "   " + signed(excess).rjust(7)
                + "  " + (format(block.get("positive_return_breadth_pct"), ".0f")
                          + "%" if block.get("positive_return_breadth_pct") is not None
                          else "n/a").rjust(6)
                + "  " + (format(block.get("up_volume_share_pct"), ".0f")
                          + "%" if block.get("up_volume_share_pct") is not None
                          else "n/a").rjust(6))
        if cmp_block:
            r = cmp_block["sectors"].get(sector, {})
            prior = r.get("prior_excess_points")
            line += "  " + (signed(prior, 0) if prior is not None else "n/a").rjust(6)
            p, t = r.get("prior_rank"), r.get("tape_rank")
            # "prior rank -> tape rank". An arrow, not an inequality: the
            # two numbers rank different things and "11 < 3" reads as a
            # false statement rather than a move up the board.
            if p is None or t is None:
                rank = "n/a"
            else:
                rank = str(p) + " -> " + str(t)
                if r.get("flag"):
                    rank += " *"
            line += "  " + rank.rjust(11)
        lines.append(line)
    return lines


def render_comparisons(tape: dict) -> list[str]:
    """Gold, the dollar and bitcoin: their own table, never rows of the chart."""
    block = tape.get(mc.BLOCK_KEY)
    horizons = list(dt.HORIZON_SESSIONS.items())
    known = {i["ticker"]: i for i in mc.INSTRUMENTS}
    rows = (block or {}).get("rows") or {}
    # The artifact's own rows when it has the block; a tape that predates the
    # block still gets every row, each saying missing.
    order = list(rows) if block else list(known)

    head, rule = "| Comparison | Reads |", "|---|---|"
    for _, n in horizons:
        head += " " + str(n) + "d | " + str(n) + "d vs SPY |"
        rule += "---:|---:|"
    lines = [
        "",
        "**Comparison rows -- not sectors.** Each instrument over the tape's own "
        "windows, and against SPY. No breadth, no volume confirmation, no score; "
        "never an input to a forecast, a payload or an evaluation.",
        "",
        head,
        rule,
    ]
    notes: list[str] = []
    for ticker in order:
        row = rows.get(ticker) or {}
        inst = known.get(ticker, {})
        label = row.get("label") or inst.get("label") or ticker
        name = row.get("name") or inst.get("name") or ""
        source = row.get("source") or (str(inst.get("block")) + "." + ticker)
        cells, reasons = [], []
        for h, _ in horizons:
            w = row.get(h) or {}
            ret, rel = w.get("return_pct"), w.get("return_vs_spy_pct")
            cells.append(format(ret, "+.2f") + "%" if ret is not None else "missing")
            cells.append(signed(rel) if rel is not None else "missing")
            for m in w.get("missing") or []:
                if m.get("reason") and m["reason"] not in reasons:
                    reasons.append(m["reason"])
        lines.append("| " + label + " | `" + source + "` " + name + " | "
                     + " | ".join(cells) + " |")
        if reasons:
            notes.append("- **" + label + "**: " + "; ".join(reasons) + ".")

    lines += ["", "Returns in percent. *vs SPY* is in percentage points, the same "
                  "subtraction as a sector's EXCESS."]
    if block is None:
        lines += ["", "- `" + tape["_path"] + "` predates the comparison rows, so "
                  "every row reads missing. Nothing is backfilled into a "
                  "published tape."]
    elif notes:
        lines += [""] + notes
    for w in (block or {}).get("warnings") or []:
        lines.append("- ⚠️ " + w)
    return lines


def render_regime_line(regime: dict, cmp_block: dict | None) -> list[str]:
    if regime.get("archetype") is None:
        return ["> ⚠️ &nbsp;**No declared regime.** " + (regime.get("reason") or "")
                + " The tape below is arithmetic only."]
    if cmp_block is None:
        return ["> ⚠️ &nbsp;**Archetype " + str(regime["archetype"])
                + " is declared but not in the matrix**, so no prior is shown. "
                  "The tape below is arithmetic only."]
    age = regime.get("age_days")
    age_txt = ("declared " + str(age) + " day" + ("s" if age != 1 else "")
               + " ago" if age is not None else "declaration undated")
    out = ["> \U0001f9ed &nbsp;**Regime prior** &nbsp; archetype "
           + str(regime["archetype"]) + ", " + str(cmp_block["archetype_name"])
           + " &nbsp;&nbsp;•&nbsp;&nbsp; " + age_txt
           + " (" + str(regime.get("declared_as_of")) + ")"
           + " &nbsp;&nbsp;•&nbsp;&nbsp; n=" + str(cmp_block["archetype_n"])
           + " episode" + ("s" if cmp_block["archetype_n"] != 1 else "")]
    return out


def render_contradictions(cmp_block: dict) -> list[str]:
    names = cmp_block["contradictions"]
    if not names:
        return ["", "No sector diverges from the archetype prior by "
                + str(cmp_block["divergence_flag_at"])
                + " rank positions or more."]
    lines = ["", "<details>",
             "<summary><b>⚠️ Where the tape contradicts the prior ("
             + str(len(names)) + ")</b></summary>", ""]
    for sector in names:
        r = cmp_block["sectors"][sector]
        direction = ("the prior ranks it a leader and the tape has it lagging"
                     if r["flag"] == "prior_leader_tape_laggard"
                     else "the prior ranks it a laggard and the tape has it leading")
        lines.append(
            "- **" + sector + "** — " + direction + ": prior "
            + signed(r["prior_excess_points"], 0) + " points (rank "
            + str(r["prior_rank"]) + " of " + str(r["prior_rank_of"])
            + "), tape " + signed(r["tape_excess_pct"]) + "% vs SPY (rank "
            + str(r["tape_rank"]) + " of " + str(r["tape_rank_of"])
            + "), " + str(r["rank_divergence"]) + " positions apart.")
    lines += ["", cmp_block["note"], "", "</details>"]
    return lines


def render_successors(archetype: int) -> list[str]:
    succ = rp.likely_successors(archetype)
    if not succ:
        return []
    total = succ[0]["of"]
    parts = [s["name"] + " (" + str(s["observed"]) + ")" for s in succ]
    return ["", "**Observed handoffs from this archetype:** " + ", ".join(parts)
            + " — " + str(total) + " transition"
            + ("s" if total != 1 else "")
            + " in the gap-free record. Too few to forecast from; recorded so "
              "the prior is not read as permanent."]


def build() -> str:
    tape = latest_tape()
    lines = [START, "", "## \U0001f4c8 Daily tape", ""]

    if tape is None:
        lines += [
            "No daily tape published. Run:",
            "",
            "    python src/daily_tape.py --panel ../weekly-council-scan/data/daily",
            "",
            END,
        ]
        return "\n".join(lines)

    regime = rp.active_regime(ROOT / "data/forecasts", tape["as_of"])
    cmp_block = None
    if regime.get("archetype") is not None:
        try:
            cmp_block = rp.compare(tape, regime["archetype"])
        except rp.PriorError:
            cmp_block = None

    lines += [
        "**As of " + tape["as_of"] + "** -- observation, not a forecast -- `"
        + tape["_path"] + "`",
        "",
        "> \U0001f4cf &nbsp;**" + str(tape["panel_sessions"])
        + " sessions** from " + tape["panel_from"] + " &nbsp;&nbsp;•&nbsp;&nbsp; "
        + "three arithmetic components over daily bars &nbsp;&nbsp;•&nbsp;&nbsp; "
        + "no score, no `regime_fit`, no `macro_catalyst`",
    ]
    lines += ["> "] + render_regime_line(regime, cmp_block)

    lines += ["", "```"] + render_chart(tape, cmp_block) + ["```"]

    if cmp_block:
        lines += render_contradictions(cmp_block)
        lines += render_successors(regime["archetype"])

    lines += render_comparisons(tape)

    warn = tape.get("warnings") or []
    if warn:
        lines += ["", "<details>",
                  "<summary><b>Panel warnings (" + str(len(warn)) + ")</b></summary>",
                  ""]
        lines += ["- " + w for w in warn]
        lines += ["", "</details>"]

    lines += [
        "",
        "> This block records what traded. It scores nothing. The two judgment "
        "components have no daily source, and a daily artifact carrying them "
        "would be inventing them -- see `docs/decisions/"
        "2026-09-11-daily-observation-tape.md`.",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("README.md has no TAPE markers")
        return 1
    head = text[: text.index(START)]
    tail = text[text.index(END) + len(END):]
    updated = head + build() + tail

    if "--check" in sys.argv:
        if updated != text:
            print("README daily tape is stale. Run: python scripts/render_tape.py")
            return 1
        print("README daily tape is up to date.")
        return 0

    README.write_text(updated, encoding="utf-8", newline="\n")
    print("Updated the README daily-tape block.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
